### ISSUE TITLE
setDemultiplyEnabled(true) looks funky with colored text

### ISSUE THREAD

**Issue by adielfernandez** [bluecadet/Cinder-BluecadetText#16]
Text gets a white halo instead of the color (set using setTextColor(ColorA col) ) of the text view:

![image](https://user-images.githubusercontent.com/2591545/49304273-daa1a380-f499-11e8-8382-67483bf2591b.png)

**Comment by benjaminbojko** [comment]
Have you tried setting demultiply to false?

**Comment by adielfernandez** [comment]
Yeah, that just gives a gray halo: 
![image](https://user-images.githubusercontent.com/2591545/49307876-88b24b00-f4a4-11e8-8192-f6a40572374f.png)

BUT: the winning combo turns out to be setting demultiply to false AND setting a PREMULT blendmode 👍
